services:
  app: 
    container_name: widget-server
    build: .
    ports:
      - 3000:$PORT
    depends_on:
      - db
    environment:
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY=$CLOUDFLARE_ACCESS_KEY
      - CLOUDFLARE_PUBLIC_BUCKET_URL=$CLOUDFLARE_PUBLIC_BUCKET_URL
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
    restart: unless-stopped

  db:
    image: bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/path/to/postgresql-persistence:/bitnami/postgresql
    restart: unless-stopped

volumes:
  db: 
