name: widget-server pipe ECR

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

jobs:
  run-ci-aws-ecr:
    name: widget-server run-ci ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 22.15

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        # with:
          # version: 8
  
      - name: Install dependencies
        id: install-dependencies
        run: pnpm install --frozen-lockfile
  
      # - name: Run Tests
      #   run: pnpm run test

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
  
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build Image
        id: build-image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate-tag.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Run Vulnerability Scanner
        id: run-trivy-scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{steps.login-ecr.outputs.registry}}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate-tag.outputs.sha }}'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Push the Image to AWS ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate-tag.outputs.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

